require('dotenv').config();
const sequelize = require('./config/database');
const Property = require('./models/Property');

const villas = [
    {
        propertyName: 'MJR Divine Meadows - 3BHK/3.5 BHK',
        projectName: 'MJR Divine Meadows',
        description: 'MJR Divine Meadows is an ultra-luxury gated villa community spanning 25 acres off Sarjapur Road, Bangalore. It is designed as a "sanctuary" that blends modern triplex architecture with expansive natural greenery and over 30 world-class amenities.',
        category: 'Villa',
        location: 'Chikka Tirupathi Road, Sarjapur.',
        price: 2.75,
        priceUnit: 'Cr',
        dimensions: '3,195 – 3,485 sq. ft.',
        configuration: '3BHK/3.5 BHK',
        status: 'Available',
        latitude: 12.8677758,
        longitude: 77.8009700,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/191222/005542',
        possessionTime: 'August 2026',
        units: '137 villas',
        floor: 'Ground + 2 Floors',
        landParcel: '25 acres',
    },
    {
        propertyName: 'MJR Divine Meadows - 4 BHK (Type A)',
        projectName: 'MJR Divine Meadows',
        description: 'MJR Divine Meadows is an ultra-luxury gated villa community spanning 25 acres off Sarjapur Road, Bangalore.',
        category: 'Villa',
        location: 'Chikka Tirupathi Road, Sarjapur.',
        price: 2.33,
        priceUnit: 'Cr',
        dimensions: '3,195 – 3,485 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 12.8677758,
        longitude: 77.8009700,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/191222/005542',
        possessionTime: 'August 2026',
        units: '137 villas',
        floor: 'Ground + 2 Floors',
        landParcel: '25 acres',
    },
    {
        propertyName: 'MJR Divine Meadows - 4 BHK (Type B)',
        projectName: 'MJR Divine Meadows',
        description: 'MJR Divine Meadows is an ultra-luxury gated villa community spanning 25 acres off Sarjapur Road, Bangalore.',
        category: 'Villa',
        location: 'Chikka Tirupathi Road, Sarjapur.',
        price: 2.33,
        priceUnit: 'Cr',
        dimensions: '3,054 – 3,901 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 12.8677758,
        longitude: 77.8009700,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/191222/005542',
        possessionTime: 'August 2026',
        units: '137 villas',
        floor: 'Ground + 2 Floors',
        landParcel: '25 acres',
    },
    {
        propertyName: 'MJR Divine Meadows - 5 BHK',
        projectName: 'MJR Divine Meadows',
        description: 'MJR Divine Meadows is an ultra-luxury gated villa community spanning 25 acres off Sarjapur Road, Bangalore.',
        category: 'Villa',
        location: 'Chikka Tirupathi Road, Sarjapur.',
        price: 3.46,
        priceUnit: 'Cr',
        dimensions: '3,901+ sq. ft.',
        configuration: '5 BHK',
        status: 'Available',
        latitude: 12.8677758,
        longitude: 77.8009700,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/191222/005542',
        possessionTime: 'August 2026',
        units: '137 villas',
        floor: 'Ground + 2 Floors',
        landParcel: '25 acres',
    },
    {
        propertyName: 'Birla Ojasvi - Row House (4/5 BHK)',
        projectName: 'Birla Ojasvi',
        description: 'Birla Ojasvi is a premium, low-density residential township by Birla Estates located in RR Nagar, South-West Bangalore.',
        category: 'Villa',
        location: 'Rajarajeshwari Nagar (RR Nagar), South-West Bangalore.',
        price: 5.65,
        priceUnit: 'Cr',
        dimensions: '3,353 sq. ft.',
        configuration: 'Row House (4/5 BHK)',
        status: 'Available',
        latitude: 12.906834,
        longitude: 77.507545,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/040924/006989',
        possessionTime: 'January 30, 2031',
        units: '8 luxury row house villas',
        floor: 'Ground + 2 Floors',
        landParcel: '10.23 acres',
    },
    {
        propertyName: 'Birla Ojasvi - 3 BHK (Signature/Iconic)',
        projectName: 'Birla Ojasvi',
        description: 'Birla Ojasvi is a premium residential township by Birla Estates.',
        category: 'Residential',
        location: 'RR Nagar, South-West Bangalore.',
        price: 2.37,
        priceUnit: 'Cr',
        dimensions: '1,361 - 1,387 sq. ft.',
        configuration: '3 BHK (Signature/Iconic)',
        status: 'Available',
        latitude: 12.906834,
        longitude: 77.507545,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/040924/006989',
        possessionTime: 'January 30, 2031',
        units: '8 luxury row house villas',
        floor: 'Ground + 2 Floors',
        landParcel: '10.23 acres',
    },
    {
        propertyName: 'Birla Ojasvi - 2 BHK Apartment',
        projectName: 'Birla Ojasvi',
        description: 'Birla Ojasvi is a premium residential township by Birla Estates.',
        category: 'Residential',
        location: 'RR Nagar, South-West Bangalore.',
        price: 1.42,
        priceUnit: 'Cr',
        dimensions: '929 - 980 sq. ft.',
        configuration: '2 BHK Apartment',
        status: 'Available',
        latitude: 12.906834,
        longitude: 77.507545,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/040924/006989',
        possessionTime: 'January 30, 2031',
        units: '8 luxury row house villas',
        floor: 'Ground + 2 Floors',
        landParcel: '10.23 acres',
    },
    {
        propertyName: 'Prestige Park Grove - 4 BHK Villas',
        projectName: 'Prestige Park Grove',
        description: 'Prestige Park Grove is an expansive, avant-garde residential township located in Seegehalli, Whitefield. It follows a visionary "Four Petals of Life" theme.',
        category: 'Villa',
        location: 'Seegehalli, Whitefield, East Bengaluru.',
        price: 5.5,
        priceUnit: 'Cr',
        dimensions: '3,463 – 4,170 sq. ft.',
        configuration: '4 BHK Villas',
        status: 'Available',
        latitude: 13.0191659,
        longitude: 77.7574142,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/100823/006141',
        possessionTime: 'December 2027',
        units: '111 luxury villas',
        floor: 'Ground + 1 Floor',
        landParcel: '75 acres',
    },
    {
        propertyName: 'Adarsh Welkin Park Villas - 3 BHK Villa',
        projectName: 'Adarsh Welkin Park Villas',
        description: 'Adarsh Welkin Park Villas is an ultra-luxury residential enclave off Sarjapur Road in Rayasandra.',
        category: 'Villa',
        location: 'Rayasandra, East Bengaluru.',
        price: 4.14,
        priceUnit: 'Cr',
        dimensions: '3,406 – 3,753 sq. ft.',
        configuration: '3 BHK Villa',
        status: 'Available',
        latitude: 12.869392072955412,
        longitude: 77.68731437301163,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/020923/006224',
        possessionTime: 'October 2027',
        units: '174 signature villas',
        floor: 'G+2 floors',
        landParcel: '51 Acres',
    },
    {
        propertyName: 'Adarsh Welkin Park Villas - 4 BHK Villa',
        projectName: 'Adarsh Welkin Park Villas',
        description: 'Adarsh Welkin Park Villas is an ultra-luxury residential enclave off Sarjapur Road in Rayasandra.',
        category: 'Villa',
        location: 'Rayasandra, East Bengaluru.',
        price: 4.40,
        priceUnit: 'Cr',
        dimensions: '3,412 – 4,834 sq. ft.',
        configuration: '4 BHK Villa',
        status: 'Available',
        latitude: 12.869392072955412,
        longitude: 77.68731437301163,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/020923/006224',
        possessionTime: 'October 2027',
        units: '174 signature villas',
        floor: 'G+2 floors',
        landParcel: '51 Acres',
    },
    {
        propertyName: 'Adarsh Welkin Park Villas - Corner/Premium',
        projectName: 'Adarsh Welkin Park Villas',
        description: 'Adarsh Welkin Park Villas is an ultra-luxury residential enclave off Sarjapur Road in Rayasandra.',
        category: 'Villa',
        location: 'Rayasandra, East Bengaluru.',
        price: 6.44,
        priceUnit: 'Cr',
        dimensions: 'Up to 4,834 sq. ft.',
        configuration: 'Corner/Premium',
        status: 'Available',
        latitude: 12.869392072955412,
        longitude: 77.68731437301163,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/020923/006224',
        possessionTime: 'October 2027',
        units: '174 signature villas',
        floor: 'G+2 floors',
        landParcel: '51 Acres',
    },
    {
        propertyName: 'Prestige Dew Drops - 3 BHK (Type 1)',
        projectName: 'Prestige Dew Drops',
        description: 'Prestige Dew Drops is an ultra-exclusive, low-density villa enclave in North Bangalore.',
        category: 'Villa',
        location: 'Yelahanka, North Bangalore.',
        price: 4.00,
        priceUnit: 'Cr',
        dimensions: '3,508 sq. ft.',
        configuration: '3 BHK',
        status: 'Available',
        latitude: 13.18,
        longitude: 77.56,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/150323/005797',
        possessionTime: 'April 2026',
        units: '25 exclusive premium villas',
        floor: 'G+2 FLOORS',
        landParcel: '5.4 acres',
    },
    {
        propertyName: 'Prestige Dew Drops - 3 BHK (Type 2)',
        projectName: 'Prestige Dew Drops',
        description: 'Prestige Dew Drops is an ultra-exclusive, low-density villa enclave in North Bangalore.',
        category: 'Villa',
        location: 'Yelahanka, North Bangalore.',
        price: 4.00,
        priceUnit: 'Cr',
        dimensions: '3,540 sq. ft.',
        configuration: '3 BHK',
        status: 'Available',
        latitude: 13.18,
        longitude: 77.56,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/150323/005797',
        possessionTime: 'April 2026',
        units: '25 exclusive premium villas',
        floor: 'G+2 FLOORS',
        landParcel: '5.4 acres',
    },
    {
        propertyName: 'Prestige Dew Drops - 4 BHK (4942 sqft)',
        projectName: 'Prestige Dew Drops',
        description: 'Prestige Dew Drops is an ultra-exclusive, low-density villa enclave in North Bangalore.',
        category: 'Villa',
        location: 'Yelahanka, North Bangalore.',
        price: 5.50,
        priceUnit: 'Cr',
        dimensions: '4,942 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 13.18,
        longitude: 77.56,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/150323/005797',
        possessionTime: 'April 2026',
        units: '25 exclusive premium villas',
        floor: 'G+2 FLOORS',
        landParcel: '5.4 acres',
    },
    {
        propertyName: 'Prestige Dew Drops - 4 BHK (5084 sqft)',
        projectName: 'Prestige Dew Drops',
        description: 'Prestige Dew Drops is an ultra-exclusive, low-density villa enclave in North Bangalore.',
        category: 'Villa',
        location: 'Yelahanka, North Bangalore.',
        price: 5.50,
        priceUnit: 'Cr',
        dimensions: '5,084 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 13.18,
        longitude: 77.56,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/150323/005797',
        possessionTime: 'April 2026',
        units: '25 exclusive premium villas',
        floor: 'G+2 FLOORS',
        landParcel: '5.4 acres',
    },
    {
        propertyName: 'Prestige Dew Drops - 4 BHK (5868 sqft)',
        projectName: 'Prestige Dew Drops',
        description: 'Prestige Dew Drops is an ultra-exclusive, low-density villa enclave in North Bangalore.',
        category: 'Villa',
        location: 'Yelahanka, North Bangalore.',
        price: 8.00,
        priceUnit: 'Cr',
        dimensions: '5,868 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 13.18,
        longitude: 77.56,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/150323/005797',
        possessionTime: 'April 2026',
        units: '25 exclusive premium villas',
        floor: 'G+2 FLOORS',
        landParcel: '5.4 acres',
    },
    {
        propertyName: 'Pursuit of a Radical Rhapsody - 3 BHK Duplex (L30)',
        projectName: 'Pursuit of a Radical Rhapsody',
        description: 'Pursuit of a Radical Rhapsody in Whitefield, Bengaluru. Homes are designed in 11 distinct typologies.',
        category: 'Villa',
        location: 'ITPL Main Road in Whitefield, Bengaluru.',
        price: 9.30,
        priceUnit: 'Cr',
        dimensions: '4,389 sq. ft.',
        configuration: '3 BHK Duplex (L30)',
        status: 'Available',
        latitude: 12.9904,
        longitude: 77.7214,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/281222/005565',
        possessionTime: 'December 2029',
        units: '68 exclusive villas',
        floor: 'G+1 FLOORS',
        landParcel: '35.07 acres',
    },
    {
        propertyName: 'Pursuit of a Radical Rhapsody - 3 BHK Duplex (D35)',
        projectName: 'Pursuit of a Radical Rhapsody',
        description: 'Pursuit of a Radical Rhapsody in Whitefield, Bengaluru. Homes are designed in 11 distinct typologies.',
        category: 'Villa',
        location: 'ITPL Main Road in Whitefield, Bengaluru.',
        price: 8.59,
        priceUnit: 'Cr',
        dimensions: '4,596 sq. ft.',
        configuration: '3 BHK Duplex (D35)',
        status: 'Available',
        latitude: 12.9904,
        longitude: 77.7214,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/281222/005565',
        possessionTime: 'December 2029',
        units: '68 exclusive villas',
        floor: 'G+1 FLOORS',
        landParcel: '35.07 acres',
    },
    {
        propertyName: 'Pursuit of a Radical Rhapsody - 4 BHK (L45)',
        projectName: 'Pursuit of a Radical Rhapsody',
        description: 'Pursuit of a Radical Rhapsody in Whitefield, Bengaluru. Homes are designed in 11 distinct typologies.',
        category: 'Villa',
        location: 'ITPL Main Road in Whitefield, Bengaluru.',
        price: 8.81,
        priceUnit: 'Cr',
        dimensions: '5,679 sq. ft.',
        configuration: '4 BHK (L45)',
        status: 'Available',
        latitude: 12.9904,
        longitude: 77.7214,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/281222/005565',
        possessionTime: 'December 2029',
        units: '68 exclusive villas',
        floor: 'G+1 FLOORS',
        landParcel: '35.07 acres',
    },
    {
        propertyName: 'Sobha Galera - 4 BHK Duplex',
        projectName: 'Sobha Galera',
        description: 'Sobha Galera is an exclusive Spanish-themed residential row house project in Kannamangala.',
        category: 'Villa',
        location: 'Kannamangala, Whitefield Extension, East Bangalore.',
        price: 4.73,
        priceUnit: 'Cr',
        dimensions: '~3,009 – 3,032 sq. ft.',
        configuration: '4 BHK Duplex',
        status: 'Available',
        latitude: 13.054459,
        longitude: 77.769281,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/050123/005601',
        possessionTime: 'December 2026',
        units: '40 exclusive row houses',
        floor: 'G+1, G+2, G+3 FLOORS',
        landParcel: '4.08 Acres',
    },
    {
        propertyName: 'Sobha Galera - 4 BHK Triplex',
        projectName: 'Sobha Galera',
        description: 'Sobha Galera is an exclusive Spanish-themed residential row house project in Kannamangala.',
        category: 'Villa',
        location: 'Kannamangala, Whitefield Extension, East Bangalore.',
        price: 6.77,
        priceUnit: 'Cr',
        dimensions: '~4,308 – 4,340 sq. ft.',
        configuration: '4 BHK Triplex',
        status: 'Available',
        latitude: 13.054459,
        longitude: 77.769281,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/050123/005601',
        possessionTime: 'December 2026',
        units: '40 exclusive row houses',
        floor: 'G+1, G+2, G+3 FLOORS',
        landParcel: '4.08 Acres',
    },
    {
        propertyName: 'Trendcon Aurelius - 4 BHK Triplex',
        projectName: 'Trendcon Aurelius',
        description: 'Trendcon Aurelius is an exclusive resort-themed gated community in Varthur.',
        category: 'Villa',
        location: 'Varthur, East Bangalore.',
        price: 2.72,
        priceUnit: 'Cr',
        dimensions: '2,581 – 2,590 sq. ft.',
        configuration: '4 BHK Triplex',
        status: 'Available',
        latitude: 12.928175,
        longitude: 77.763125,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211223/006504',
        possessionTime: 'June 2026',
        units: '225 premium independent villas',
        floor: 'Ground + 2 Floors',
        landParcel: '12 acres',
    },
    {
        propertyName: 'Trendcon Aurelius - 5 BHK Triplex',
        projectName: 'Trendcon Aurelius',
        description: 'Trendcon Aurelius is an exclusive resort-themed gated community in Varthur.',
        category: 'Villa',
        location: 'Varthur, East Bangalore.',
        price: 3.33,
        priceUnit: 'Cr',
        dimensions: '3,177 – 3,182 sq. ft.',
        configuration: '5 BHK Triplex',
        status: 'Available',
        latitude: 12.928175,
        longitude: 77.763125,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211223/006504',
        possessionTime: 'June 2026',
        units: '225 premium independent villas',
        floor: 'Ground + 2 Floors',
        landParcel: '12 acres',
    },
    {
        propertyName: 'Purva Sparkling Springs - 3 BHK Villa',
        projectName: 'Purva Sparkling Springs',
        description: 'Purva Sparkling Springs is an ultra-luxury, nature-inspired villa retreat off Bannerghatta Road.',
        category: 'Villa',
        location: 'Bannerghatta Road, South Bengaluru.',
        price: 3.93,
        priceUnit: 'Cr',
        dimensions: '2,611 – 4,477 sq. ft.',
        configuration: '3 BHK Villa',
        status: 'Available',
        latitude: 12.850867,
        longitude: 77.604293,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/210907/004300',
        possessionTime: 'June 2026',
        units: '207 luxury villas',
        floor: 'G + 1 FLOORS',
        landParcel: '20 acres',
    },
    {
        propertyName: 'Purva Sparkling Springs - 4 BHK Villa',
        projectName: 'Purva Sparkling Springs',
        description: 'Purva Sparkling Springs is an ultra-luxury, nature-inspired villa retreat off Bannerghatta Road.',
        category: 'Villa',
        location: 'Bannerghatta Road, South Bengaluru.',
        price: 5.00,
        priceUnit: 'Cr',
        dimensions: '3,333 – 5,528 sq. ft.',
        configuration: '4 BHK Villa',
        status: 'Available',
        latitude: 12.850867,
        longitude: 77.604293,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/210907/004300',
        possessionTime: 'June 2026',
        units: '207 luxury villas',
        floor: 'G + 1 FLOORS',
        landParcel: '20 acres',
    },
    {
        propertyName: 'Atmos Tropicalwoods - 3 BHK Villa (2270 sqft)',
        projectName: 'Atmos Tropicalwoods',
        description: 'Atmos Tropicalwoods is a climate-smart luxury villa community on Doddaballapur Road.',
        category: 'Villa',
        location: 'Yelahanka-Doddaballapur Main Road, North Bangalore.',
        price: 1.81,
        priceUnit: 'Cr',
        dimensions: '2,270 sq. ft.',
        configuration: '3 BHK Villa',
        status: 'Available',
        latitude: 13.201542,
        longitude: 77.546120,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/111124/007218',
        possessionTime: 'September 2027',
        units: '150 units',
        floor: 'Ground + 2 Floors',
        landParcel: '7 acres',
    },
    {
        propertyName: 'Atmos Tropicalwoods - 3 BHK Villa (2324 sqft)',
        projectName: 'Atmos Tropicalwoods',
        description: 'Atmos Tropicalwoods is a climate-smart luxury villa community on Doddaballapur Road.',
        category: 'Villa',
        location: 'Yelahanka-Doddaballapur Main Road, North Bangalore.',
        price: 1.93,
        priceUnit: 'Cr',
        dimensions: '2,324 sq. ft.',
        configuration: '3 BHK Villa',
        status: 'Available',
        latitude: 13.201542,
        longitude: 77.546120,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/111124/007218',
        possessionTime: 'September 2027',
        units: '150 units',
        floor: 'Ground + 2 Floors',
        landParcel: '7 acres',
    },
    {
        propertyName: 'Atmos Tropicalwoods - 3 BHK Villa (2370 sqft)',
        projectName: 'Atmos Tropicalwoods',
        description: 'Atmos Tropicalwoods is a climate-smart luxury villa community on Doddaballapur Road.',
        category: 'Villa',
        location: 'Yelahanka-Doddaballapur Main Road, North Bangalore.',
        price: 2.13,
        priceUnit: 'Cr',
        dimensions: '2,370 sq. ft.',
        configuration: '3 BHK Villa',
        status: 'Available',
        latitude: 13.201542,
        longitude: 77.546120,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/111124/007218',
        possessionTime: 'September 2027',
        units: '150 units',
        floor: 'Ground + 2 Floors',
        landParcel: '7 acres',
    },
    {
        propertyName: 'Atmos Tropicalwoods - 4 BHK Villa (3750 sqft)',
        projectName: 'Atmos Tropicalwoods',
        description: 'Atmos Tropicalwoods is a climate-smart luxury villa community on Doddaballapur Road.',
        category: 'Villa',
        location: 'Yelahanka-Doddaballapur Main Road, North Bangalore.',
        price: 2.42,
        priceUnit: 'Cr',
        dimensions: '3,750 sq. ft.',
        configuration: '4 BHK Villa',
        status: 'Available',
        latitude: 13.201542,
        longitude: 77.546120,
        reraNumber: 'PRM/KA/RERA/1251/472/PR/111124/007218',
        possessionTime: 'September 2027',
        units: '150 units',
        floor: 'Ground + 2 Floors',
        landParcel: '7 acres',
    },
    {
        propertyName: 'Woodsvale - 4 BHK (2230 sqft)',
        projectName: 'Woodsvale',
        description: 'Tattvam Woodsvale is a 22-acre sustainable luxury enclave off Sarjapur Road.',
        category: 'Villa',
        location: 'Sarjapur Road, Bangalore.',
        price: 2.24,
        priceUnit: 'Cr',
        dimensions: '2,230 - 2,255 sq. ft.',
        configuration: '4 BHK',
        status: 'RTMI',
        latitude: 12.8687,
        longitude: 77.7818,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211007/004348',
        possessionTime: 'December 2024',
        units: '145 Villas',
        floor: 'Ground + 1, Ground + 2 Floors',
        landParcel: '22 acres',
    },
    {
        propertyName: 'Woodsvale - 4 BHK (2450 sqft)',
        projectName: 'Woodsvale',
        description: 'Tattvam Woodsvale is a 22-acre sustainable luxury enclave.',
        category: 'Villa',
        location: 'Sarjapur Road, Bangalore.',
        price: 2.57,
        priceUnit: 'Cr',
        dimensions: '2,450 - 2,454 sq. ft.',
        configuration: '4 BHK',
        status: 'RTMI',
        latitude: 12.8687,
        longitude: 77.7818,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211007/004348',
        possessionTime: 'December 2024',
        units: '145 Villas',
        floor: 'Ground + 1, Ground + 2 Floors',
        landParcel: '22 acres',
    },
    {
        propertyName: 'Woodsvale - 4 BHK (2803 sqft)',
        projectName: 'Woodsvale',
        description: 'Tattvam Woodsvale is a 22-acre sustainable luxury enclave.',
        category: 'Villa',
        location: 'Sarjapur Road, Bangalore.',
        price: 2.84,
        priceUnit: 'Cr',
        dimensions: '2,803 - 2,867 sq. ft.',
        configuration: '4 BHK',
        status: 'RTMI',
        latitude: 12.8687,
        longitude: 77.7818,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211007/004348',
        possessionTime: 'December 2024',
        units: '145 Villas',
        floor: 'Ground + 1, Ground + 2 Floors',
        landParcel: '22 acres',
    },
    {
        propertyName: 'Woodsvale - 5 BHK (3370 sqft)',
        projectName: 'Woodsvale',
        description: 'Tattvam Woodsvale is a 22-acre sustainable luxury enclave.',
        category: 'Villa',
        location: 'Sarjapur Road, Bangalore.',
        price: 3.36,
        priceUnit: 'Cr',
        dimensions: '3,370 - 3,403 sq. ft.',
        configuration: '5 BHK',
        status: 'RTMI',
        latitude: 12.8687,
        longitude: 77.7818,
        reraNumber: 'PRM/KA/RERA/1251/308/PR/211007/004348',
        possessionTime: 'December 2024',
        units: '145 Villas',
        floor: 'Ground + 1, Ground + 2 Floors',
        landParcel: '22 acres',
    },
    {
        propertyName: 'Urbanrise Paradise on Earth - 4 BHK',
        projectName: 'Urbanrise Paradise on Earth',
        description: 'Urbanrise Paradise on Earth is an IGBC Platinum pre-certified luxury villa project on Kanakapura Road.',
        category: 'Villa',
        location: 'Gangasandra, off Kanakapura Road, Bangalore.',
        price: 3.02,
        priceUnit: 'Cr',
        dimensions: '2,434 to 3,579 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        latitude: 12.84,
        longitude: 77.46,
        reraNumber: 'PRM/KA/RERA/1251/310/PR/080223/005704',
        possessionTime: 'January 2026',
        units: '219 triplex villas',
        floor: 'G+2 floors',
        landParcel: '24-acre',
    },
    {
        propertyName: 'Soul Street by Navavedam - 4 BHK Row House',
        projectName: 'Soul Street by Navavedam',
        description: 'Soul Street by Navavedam is a Scandinavian-inspired, ultra-luxury boutique development in Budigere Cross.',
        category: 'Villa',
        location: 'Budigere Cross, East Bengaluru.',
        price: 3.03,
        priceUnit: 'Cr',
        dimensions: '2,271 to 4185 sq.ft.',
        configuration: '4 BHK Row House',
        status: 'Available',
        latitude: 13.060574,
        longitude: 77.760749,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/250924/007067',
        possessionTime: 'March 2028',
        units: '40 Exclusive Homes',
        floor: 'G+2',
        landParcel: '2 Acres',
    },
    {
        propertyName: 'Soul Street by Navavedam - 5 BHK Villa',
        projectName: 'Soul Street by Navavedam',
        description: 'Soul Street by Navavedam is a Scandinavian-inspired, ultra-luxury boutique development.',
        category: 'Villa',
        location: 'Budigere Cross, East Bengaluru.',
        price: 2.99,
        priceUnit: 'Cr',
        dimensions: '3,566 sq. ft.',
        configuration: '5 BHK Villa',
        status: 'Available',
        latitude: 13.060574,
        longitude: 77.760749,
        reraNumber: 'PRM/KA/RERA/1251/446/PR/250924/007067',
        possessionTime: 'March 2028',
        units: '40 Exclusive Homes',
        floor: 'G+2',
        landParcel: '2 Acres',
    },
    {
        propertyName: 'ATMOS VILASA - 4 BHK Villa (Standard)',
        projectName: 'ATMOS VILASA',
        description: 'Atmos Vilasa is an exclusive community of 44 luxury 4 BHK villas in Rajanukunte.',
        category: 'Villa',
        location: 'Rajanukunte, North Bengaluru.',
        price: 2.29,
        priceUnit: 'Cr',
        dimensions: '2,651 sq.ft.',
        configuration: '4 BHK Villa (Standard)',
        status: 'Available',
        latitude: 13.184393,
        longitude: 77.544639,
        reraNumber: 'PRM/KA/RERA/1251/309/PR/241115/006178',
        possessionTime: 'December 2027',
        units: '44 exclusive units',
        floor: 'Ground + 2 Floors',
        landParcel: '4 acres',
    },
    {
        propertyName: 'ATMOS VILASA - 4 BHK Villa (Large)',
        projectName: 'ATMOS VILASA',
        description: 'Atmos Vilasa is an exclusive community of 44 luxury 4 BHK villas in Rajanukunte.',
        category: 'Villa',
        location: 'Rajanukunte, North Bengaluru.',
        price: 2.85,
        priceUnit: 'Cr',
        dimensions: '3,300 sq.ft.',
        configuration: '4 BHK Villa (Large)',
        status: 'Available',
        latitude: 13.184393,
        longitude: 77.544639,
        reraNumber: 'PRM/KA/RERA/1251/309/PR/241115/006178',
        possessionTime: 'December 2027',
        units: '44 exclusive units',
        floor: 'Ground + 2 Floors',
        landParcel: '4 acres',
    },
];

async function seed() {
    try {
        await sequelize.authenticate();
        console.log('Database connected.');

        // Sync to ensure table exists
        await sequelize.sync();

        for (const villa of villas) {
            await Property.create(villa);
            console.log(`Created: ${villa.propertyName}`);
        }

        console.log('Seeding completed successfully.');
        process.exit(0);
    } catch (error) {
        console.error('Seeding failed:', error);
        process.exit(1);
    }
}

seed();
