require('dotenv').config();
const sequelize = require('./config/database');
const Property = require('./models/Property');

const properties = [
    // ========== ONE GOA ==========
    {
        propertyName: 'One Goa - Standard Plot',
        projectName: 'One Goa',
        description: 'Premium residential plots in Bicholim, North Goa. 1,248 sq. ft. standard plot in a gated community with world-class amenities. Possession by March 2029.',
        category: 'Plot',
        location: 'Bicholim, North Goa',
        price: 83,
        priceUnit: 'Lakhs',
        dimensions: '1,248 sq. ft.',
        configuration: 'Standard Plot',
        status: 'Available',
        amenities: ['Gated Community', 'Landscaping', 'Club House', '24/7 Security', 'Power Backup'],
        photos: [],
    },
    {
        propertyName: 'One Goa - Premium Plot',
        projectName: 'One Goa',
        description: 'Premium plot (43.97 ft x 35 ft) in Bicholim, North Goa. 1,539 sq. ft. with excellent road connectivity and serene surroundings. Possession by March 2029.',
        category: 'Plot',
        location: 'Bicholim, North Goa',
        price: 1.00,
        priceUnit: 'Cr',
        dimensions: '1,539 sq. ft. (43.97 ft x 35 ft)',
        configuration: 'Premium Plot',
        status: 'Available',
        amenities: ['Gated Community', 'Landscaping', 'Club House', '24/7 Security', 'Power Backup'],
        photos: [],
    },
    {
        propertyName: 'One Goa - Grand Villa Estate',
        projectName: 'One Goa',
        description: 'Grand villa estate plot of 1,851 sq. ft. in Bicholim, North Goa. Perfect for building your dream villa in Goa. Possession by March 2029.',
        category: 'Plot',
        location: 'Bicholim, North Goa',
        price: 1.20,
        priceUnit: 'Cr',
        dimensions: '1,851 sq. ft.',
        configuration: 'Grand Villa Estate',
        status: 'Available',
        amenities: ['Gated Community', 'Landscaping', 'Club House', '24/7 Security', 'Power Backup', 'Swimming Pool'],
        photos: [],
    },
    {
        propertyName: 'One Goa - Elite Range',
        projectName: 'One Goa',
        description: 'Elite range plot of 2,400 sq. ft. in Bicholim, North Goa. Spacious premium plot for luxury villa construction. Possession by March 2029.',
        category: 'Plot',
        location: 'Bicholim, North Goa',
        price: 1.56,
        priceUnit: 'Cr',
        dimensions: '2,400 sq. ft.',
        configuration: 'Elite Range',
        status: 'Available',
        amenities: ['Gated Community', 'Landscaping', 'Club House', '24/7 Security', 'Power Backup', 'Swimming Pool', 'Gym'],
        photos: [],
    },

    // ========== SOBHA TOWN PARK PHASE 3 ==========
    {
        propertyName: 'Sobha Town Park Phase 3 - 1 BHK',
        projectName: 'Sobha Town Park Phase 3',
        description: 'Affordable 1 BHK apartment by Sobha Developers near Electronic City, Bengaluru. 753 sq. ft. with premium specifications. Possession by December 2030.',
        category: 'Residential',
        location: 'Yadavanahalli, Electronic City, Bengaluru',
        price: 90,
        priceUnit: 'Lakhs',
        dimensions: '753 sq. ft.',
        configuration: '1 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Children\'s Play Area', 'Clubhouse', 'Jogging Track', 'Power Backup', 'Lift'],
        photos: [],
    },
    {
        propertyName: 'Sobha Town Park Phase 3 - 2 BHK',
        projectName: 'Sobha Town Park Phase 3',
        description: 'Spacious 2 BHK apartment by Sobha Developers near Electronic City, Bengaluru. 1,240–1,330 sq. ft. with modern amenities. Possession by December 2030.',
        category: 'Residential',
        location: 'Yadavanahalli, Electronic City, Bengaluru',
        price: 1.74,
        priceUnit: 'Cr',
        dimensions: '1,240 - 1,330 sq. ft.',
        configuration: '2 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Children\'s Play Area', 'Clubhouse', 'Jogging Track', 'Power Backup', 'Lift'],
        photos: [],
    },
    {
        propertyName: 'Sobha Town Park Phase 3 - 3 BHK',
        projectName: 'Sobha Town Park Phase 3',
        description: 'Premium 3 BHK apartment by Sobha Developers near Electronic City, Bengaluru. 1,514–1,842 sq. ft. with top-tier specifications. Possession by December 2030.',
        category: 'Residential',
        location: 'Yadavanahalli, Electronic City, Bengaluru',
        price: 2.12,
        priceUnit: 'Cr',
        dimensions: '1,514 - 1,842 sq. ft.',
        configuration: '3 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Children\'s Play Area', 'Clubhouse', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden'],
        photos: [],
    },
    {
        propertyName: 'Sobha Town Park Phase 3 - 4 BHK',
        projectName: 'Sobha Town Park Phase 3',
        description: 'Luxury 4 BHK apartment by Sobha Developers near Electronic City, Bengaluru. 2,203–2,846 sq. ft. with world-class amenities. Possession by December 2030.',
        category: 'Residential',
        location: 'Yadavanahalli, Electronic City, Bengaluru',
        price: 3.08,
        priceUnit: 'Cr',
        dimensions: '2,203 - 2,846 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Children\'s Play Area', 'Clubhouse', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden', 'Indoor Games'],
        photos: [],
    },

    // ========== ABHEE CELESTIAL CITY PHASE 2 ==========
    {
        propertyName: 'Abhee Celestial City Phase 2 - 2 BHK',
        projectName: 'Abhee Celestial City Phase 2',
        description: '2 BHK + 2T apartment on Whitefield–Sarjapur Main Road, East Bangalore. 1,340–1,350 sq. ft. at ₹10,800/sq. ft. Possession by June 2029.',
        category: 'Residential',
        location: 'Whitefield-Sarjapur Main Road, East Bangalore',
        price: 1.31,
        priceUnit: 'Cr',
        dimensions: '1,340 - 1,350 sq. ft.',
        configuration: '2 BHK + 2T',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Rainwater Harvesting'],
        photos: [],
    },
    {
        propertyName: 'Abhee Celestial City Phase 2 - 2.5 BHK',
        projectName: 'Abhee Celestial City Phase 2',
        description: '2.5 BHK (3 BHK + 2T) apartment on Whitefield–Sarjapur Main Road, East Bangalore. 1,680–1,685 sq. ft. Possession by June 2029.',
        category: 'Residential',
        location: 'Whitefield-Sarjapur Main Road, East Bangalore',
        price: 1.81,
        priceUnit: 'Cr',
        dimensions: '1,680 - 1,685 sq. ft.',
        configuration: '2.5 BHK (3 BHK + 2T)',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Rainwater Harvesting'],
        photos: [],
    },
    {
        propertyName: 'Abhee Celestial City Phase 2 - 3 BHK Medium',
        projectName: 'Abhee Celestial City Phase 2',
        description: '3 BHK (Medium) apartment on Whitefield–Sarjapur Main Road, East Bangalore. 1,595–1,700 sq. ft. Possession by June 2029.',
        category: 'Residential',
        location: 'Whitefield-Sarjapur Main Road, East Bangalore',
        price: 1.72,
        priceUnit: 'Cr',
        dimensions: '1,595 - 1,700 sq. ft.',
        configuration: '3 BHK (Medium)',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Rainwater Harvesting'],
        photos: [],
    },
    {
        propertyName: 'Abhee Celestial City Phase 2 - 3 BHK Large',
        projectName: 'Abhee Celestial City Phase 2',
        description: '3 BHK (Large) apartment on Whitefield–Sarjapur Main Road, East Bangalore. 1,895–1,990 sq. ft. Possession by June 2029.',
        category: 'Residential',
        location: 'Whitefield-Sarjapur Main Road, East Bangalore',
        price: 2.05,
        priceUnit: 'Cr',
        dimensions: '1,895 - 1,990 sq. ft.',
        configuration: '3 BHK (Large)',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Rainwater Harvesting'],
        photos: [],
    },
    {
        propertyName: 'Abhee Celestial City Phase 2 - 4 BHK',
        projectName: 'Abhee Celestial City Phase 2',
        description: 'Spacious 4 BHK apartment on Whitefield–Sarjapur Main Road, East Bangalore. 2,200–2,454 sq. ft. Possession by June 2029.',
        category: 'Residential',
        location: 'Whitefield-Sarjapur Main Road, East Bangalore',
        price: 2.38,
        priceUnit: 'Cr',
        dimensions: '2,200 - 2,454 sq. ft.',
        configuration: '4 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Rainwater Harvesting', 'Indoor Games'],
        photos: [],
    },

    // ========== DOUBLE UP EOI ==========
    {
        propertyName: 'Double Up EOI - 1200 sq.ft Plot',
        projectName: 'Double Up EOI',
        description: 'Affordable 1,200 sq. ft. plot in Doddaballapur, North Bangalore at ₹3,799/sq. ft. Expression of Interest open. Possession by September 2028.',
        category: 'Plot',
        location: 'Doddaballapur, North Bangalore',
        price: 46,
        priceUnit: 'Lakhs',
        dimensions: '1,200 sq. ft.',
        configuration: 'Standard Plot',
        status: 'EOI',
        amenities: ['Gated Community', 'Internal Roads', 'Drainage', 'Electricity', 'Water Supply'],
        photos: [],
    },
    {
        propertyName: 'Double Up EOI - 1500 sq.ft Plot',
        projectName: 'Double Up EOI',
        description: 'Spacious 1,500 sq. ft. plot in Doddaballapur, North Bangalore at ₹3,799/sq. ft. Expression of Interest open. Possession by September 2028.',
        category: 'Plot',
        location: 'Doddaballapur, North Bangalore',
        price: 57,
        priceUnit: 'Lakhs',
        dimensions: '1,500 sq. ft.',
        configuration: 'Premium Plot',
        status: 'EOI',
        amenities: ['Gated Community', 'Internal Roads', 'Drainage', 'Electricity', 'Water Supply'],
        photos: [],
    },

    // ========== SATTVA LUMINA ==========
    {
        propertyName: 'Sattva Lumina - 1 BHK',
        projectName: 'Sattva Lumina',
        description: 'Affordable 1 BHK apartment in Rajanukunte, Yelahanka, North Bangalore. 650–690 sq. ft. at ₹9,597–₹10,316/sq. ft. Possession by December 2028 to late 2029.',
        category: 'Residential',
        location: 'Doddaballapura Main Road, Rajanukunte, Yelahanka, North Bangalore',
        price: 62,
        priceUnit: 'Lakhs',
        dimensions: '650 - 690 sq. ft.',
        configuration: '1 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden'],
        photos: [],
    },
    {
        propertyName: 'Sattva Lumina - 2 BHK',
        projectName: 'Sattva Lumina',
        description: 'Spacious 2 BHK apartment in Rajanukunte, Yelahanka, North Bangalore. 1,100–1,150 sq. ft. Possession by December 2028 to late 2029.',
        category: 'Residential',
        location: 'Doddaballapura Main Road, Rajanukunte, Yelahanka, North Bangalore',
        price: 1.06,
        priceUnit: 'Cr',
        dimensions: '1,100 - 1,150 sq. ft.',
        configuration: '2 BHK',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden'],
        photos: [],
    },
    {
        propertyName: 'Sattva Lumina - 3 BHK Regular',
        projectName: 'Sattva Lumina',
        description: '3 BHK Regular apartment in Rajanukunte, Yelahanka, North Bangalore. 1,450–1,506 sq. ft. Possession by December 2028 to late 2029.',
        category: 'Residential',
        location: 'Doddaballapura Main Road, Rajanukunte, Yelahanka, North Bangalore',
        price: 1.39,
        priceUnit: 'Cr',
        dimensions: '1,450 - 1,506 sq. ft.',
        configuration: '3 BHK Regular',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden', 'Indoor Games'],
        photos: [],
    },
    {
        propertyName: 'Sattva Lumina - 3 BHK Grand',
        projectName: 'Sattva Lumina',
        description: '3 BHK Grand apartment in Rajanukunte, Yelahanka, North Bangalore. 1,730–1,809 sq. ft. Premium finishes. Possession by December 2028 to late 2029.',
        category: 'Residential',
        location: 'Doddaballapura Main Road, Rajanukunte, Yelahanka, North Bangalore',
        price: 1.66,
        priceUnit: 'Cr',
        dimensions: '1,730 - 1,809 sq. ft.',
        configuration: '3 BHK Grand',
        status: 'Available',
        amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Children\'s Play Area', 'Jogging Track', 'Power Backup', 'Lift', 'Landscaped Garden', 'Indoor Games', 'Amphitheatre'],
        photos: [],
    },
];

async function seed() {
    try {
        await sequelize.authenticate();
        await sequelize.sync();

        console.log('\n🏗️  Seeding properties...\n');

        for (const prop of properties) {
            const created = await Property.create(prop);
            console.log(`  ✅ ${prop.propertyName} — ₹${prop.price} ${prop.priceUnit}`);
        }

        console.log(`\n🎉 Successfully seeded ${properties.length} properties!\n`);
        process.exit(0);
    } catch (err) {
        console.error('❌ Seeding failed:', err.message);
        process.exit(1);
    }
}

seed();
